name: tor-snowflake
base: core24
version: 'v2.10.1'
summary: Snowflake proxy
description: Snowflake proxy for Tor
grade: stable
confinement: strict

apps:
  snowflake:
    command: bin/proxy -log $SNAP_DATA/snowflake.log
    daemon: simple
    plugs:
      - network
      - network-bind

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x

parts:
  snowflake:
    source: https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake.git
    source-type: git
    source-tag: 'v2.10.1'
    source-subdir: proxy
    plugin: go
    build-snaps: [go/latest/stable]
