name: tor-snowflake
base: core24
version: 'v2.11.0'
summary: Snowflake proxy
description: Snowflake proxy for Tor
grade: stable
confinement: strict

apps:
  snowflake:
    command: bin/proxy -log $SNAP_DATA/snowflake.log
    daemon: simple
    plugs:
      - network
      - network-bind

platforms:
  amd64:
  arm64:
  armhf:
  ppc64el:
  s390x:

parts:
  snowflake:
    source: https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake.git
    source-type: git
    source-tag: 'v2.11.0'
    source-subdir: proxy
    plugin: go
    build-snaps: [go/latest/stable]
